// Importing this module pulls in RAW_DEV_HOURS_DATA (an embedded copy of the
// generated dev-hours-timesheet.csv). Server-only for the same reason as
// hoursSavedLoader.ts -- keeps it out of the client bundle.
import 'server-only';

import { RAW_DEV_HOURS_DATA } from './rawDevHoursData';
import { splitCsvLine } from './csvParse';

export interface DevHoursRow {
  engagementCode: string;
  monthlyDevHours: Record<string, number>;
  totalDevHours: number;
}

const getFs = () => {
  try {
    return typeof window === 'undefined' ? require('fs') : null;
  } catch (_e) {
    return null;
  }
};

const getPath = () => {
  try {
    return typeof window === 'undefined' ? require('path') : null;
  } catch (_e) {
    return null;
  }
};

let _cache: DevHoursRow[] | null = null;

// Unlike actuals-planned-overall-*.csv, this file is generated by
// scripts/generateDevHoursCsv.js (run manually, same convention as
// embed-csv.js) rather than being a dated external export, so it always has
// this exact fixed name.
const DEV_HOURS_FILENAME = 'dev-hours-timesheet.csv';

function getDevHoursFilePath(): string {
  if (typeof window !== 'undefined') return '';
  const fs = getFs();
  const path = getPath();
  if (!fs || !path) return '';

  const possibleDirs = [
    path.join(process.cwd(), 'public'),
    process.cwd(),
    path.join(process.cwd(), '.next', 'standalone', 'public'),
    path.join(process.cwd(), '.next', 'standalone'),
    path.join(__dirname, '..', '..', '..', 'public'),
    path.join(__dirname, '..', '..', '..'),
  ];

  for (const dir of possibleDirs) {
    try {
      const candidate = path.join(dir, DEV_HOURS_FILENAME);
      if (fs.existsSync && fs.existsSync(candidate)) return candidate;
    } catch (_err) {
      // Ignore fs permission/absence errors in edge runtimes
    }
  }

  // Not found on disk -- loadDevHoursData()'s caller falls back to the
  // embedded RAW_DEV_HOURS_DATA constant when this is empty.
  return '';
}

const MONTH_ABBREVIATIONS = new Set([
  'jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec',
]);

function isMonthColumn(header: string): boolean {
  return MONTH_ABBREVIATIONS.has(header.trim().toLowerCase().slice(0, 3));
}

/**
 * Parses dev-hours-timesheet.csv by HEADER NAME (Engagement Code + any month
 * columns), the same approach as hoursSavedLoader.ts, so this stays
 * resilient to column reordering even though this particular file is
 * generated by this app and therefore always has a known shape today.
 */
export function parseRawDevHoursText(raw: string): DevHoursRow[] {
  const lines = raw.split('\n').map((l) => l.trim()).filter((l) => l.length > 0);
  if (lines.length < 2) return [];

  const header = splitCsvLine(lines[0]).map((h) => h.trim());
  const engagementCodeIdx = header.findIndex((h) => h.toLowerCase() === 'engagement code');
  if (engagementCodeIdx === -1) return [];

  const monthColumns = header
    .map((label, idx) => ({ label, idx }))
    .filter(({ label }) => isMonthColumn(label));

  const rows: DevHoursRow[] = [];
  for (let i = 1; i < lines.length; i++) {
    const cols = splitCsvLine(lines[i]);
    const engagementCode = (cols[engagementCodeIdx] || '').trim();
    if (!engagementCode) continue;

    const monthlyDevHours: Record<string, number> = {};
    let totalDevHours = 0;
    for (const { label, idx } of monthColumns) {
      const hrs = parseFloat((cols[idx] || '').trim()) || 0;
      monthlyDevHours[label] = hrs;
      totalDevHours += hrs;
    }

    rows.push({ engagementCode, monthlyDevHours, totalDevHours });
  }

  return rows;
}

/**
 * Load and parse dev-hours-timesheet.csv from the file system, or the
 * embedded string fallback when a filesystem read isn't available (e.g. edge
 * runtimes). Results are cached in-memory for the lifetime of the server
 * process.
 */
export function loadDevHoursData(): DevHoursRow[] {
  if (_cache) return _cache;

  let raw = '';
  try {
    const fsModule = getFs();
    const csvPath = getDevHoursFilePath();
    if (fsModule && fsModule.readFileSync && csvPath) {
      raw = fsModule.readFileSync(/*turbopackIgnore: true*/ csvPath, 'utf-8');
    }
  } catch (_err) {
    raw = RAW_DEV_HOURS_DATA;
  }

  if (!raw || raw.trim().length === 0) {
    raw = RAW_DEV_HOURS_DATA;
  }

  _cache = parseRawDevHoursText(raw);
  return _cache;
}

export function clearDevHoursCache() {
  _cache = null;
}
